source = ~/.config/hypr/hyprland/*

#Monitors configuration and it's initial workspaces
monitor=DP-1,2560x1440@200,auto,auto
monitor=DP-2,1920x1080@75,auto-center-left,auto

workspace = 1, default:true, monitor:DP-1
workspace = 9, default:true, monitor:DP-2

