#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = nm-applet &
# exec-once = waybar & hyprpaper & firefox
exec-once = swaybg -i ~/.config/wallpaper -m fill
exec-once = while true; do waybar; done
exec-once = hyprctl setcursor Bibata-Modern-Ice 16

exec-once=kdeconnectd
exec-once=kdeconnect-indicator
