
##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

#Blur alacritty terminal
#windowrule = match:class Alacritty opacity 0.8 0.6
windowrule = match:class ^(Alacritty)$, opacity 0.86 0.6

#Blur rofi launcher
#layerrule = match:namespace rofi, blur on, ignore_alpha 0, no_anim on
layerrule = match:namespace wofi, no_anim on
layerrule = match:namespace notifications, blur on, ignore_alpha 0

# Fix issues with lmms
windowrule = match:class lmms.bin, no_initial_focus 1
windowrule = match:class lmms*, no_initial_focus 1

#Smart gaps
workspace = w[tv1], gapsout:0, gapsin:0
workspace = f[1], gapsout:0, gapsin:0
windowrule = border_size 0, match:float 0, match:workspace w[tv1]
windowrule = rounding 0, match:float 0, match:workspace w[tv1]
windowrule = border_size 0, match:float 0, match:workspace f[1]
windowrule = rounding 0, match:float 0, match:workspace f[1]
